### PR TITLE
Add support for binary data and fix equality check

### PR DESCRIPTION
**Pull request by eplightning**
#### What this PR does / why we need it:

Currently there's no way to add binary data to generated secrets (short of manually base64 encoding/decoding them inside both the secret and the pod).

This PR adds new `binaryData` field which allows users to put base64 binary data which will be correctly handled by Kubernetes. Generated secrets contain both `binaryData` and `data` keys merged together - with `data` taking the precedence in case of conflict.

As a nice side-effect this PR also stops operator from constantly refreshing secrets even when there were no changes. This didn't work previously because stringData is not correctly handled by `apiequality.Semantic.DeepEqual`

### CODE REVIEW

**Comment by isindir** [comment]
I need to try this, but looks that SopsSecrets will need to always have base64 encoded values ? StringData was used for ability not to do base64 wrapping outside of `sops` editor.

**Comment by eplightning** [comment]
You're right I think I was testing it on wrong CRD. I'll fix it and resubmit for review

**Comment by isindir** [comment]
Can you also please add changes in top level readme to document this feature ?

**Comment by eplightning** [comment]
Base64 decoding is now done by operator directly so it should work with data wrapped by SOPS just like text data. Sorry for the mess, was testing it on wrong code.

I've updated example secret YAML in README.md with binary data, will that be sufficient?

**Comment by isindir** [comment]
I'll still need to try locally and update accordingly to release. Thank you for your contribution.

**Comment by isindir** [comment]
merged as part of a separate PR. Thanks for contribution

**Pull request closed without merging**
